# Generated by Django 5.2.5 on 2025-09-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scripture',
            old_name='text',
            new_name='scripture_text',
        ),
        migrations.RemoveField(
            model_name='scripture',
            name='day',
        ),
        migrations.RemoveField(
            model_name='scripture',
            name='month',
        ),
        migrations.RemoveField(
            model_name='scripture',
            name='title',
        ),
        migrations.RemoveField(
            model_name='scripture',
            name='year',
        ),
        migrations.AddField(
            model_name='scripture',
            name='scripture_book',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scripture',
            name='scripture_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scripture',
            name='scripture_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scripture',
            name='scripture_testament',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scripture',
            name='scripture_verse',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
