# Generated by Django 5.2.5 on 2025-09-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_rename_text_scripture_scripture_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paschalion',
            fields=[
                ('ps_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ps_idx', models.IntegerField()),
                ('ps_sid', models.IntegerField()),
                ('ps_text', models.CharField(blank=True, max_length=200, null=True)),
                ('ps_ctext', models.CharField(blank=True, max_length=200, null=True)),
                ('ps_fname', models.CharField(blank=True, max_length=200, null=True)),
                ('ps_flevel', models.IntegerField()),
                ('ps_fast', models.IntegerField()),
                ('ps_icon', models.CharField(blank=True, max_length=200, null=True)),
                ('ps_flag', models.IntegerField()),
                ('ps_sermon_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pericope',
            fields=[
                ('pe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pe_month', models.IntegerField()),
                ('pe_day', models.IntegerField()),
                ('pe_pday', models.IntegerField()),
                ('pe_type', models.CharField(max_length=50)),
                ('pe_desc', models.TextField(blank=True, null=True)),
                ('pe_reading', models.CharField(max_length=50)),
                ('pe_display', models.CharField(max_length=200)),
                ('pe_index', models.IntegerField()),
                ('pe_flag', models.IntegerField()),
            ],
        ),
    ]
