# Generated by Django 5.2.5 on 2025-09-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tropar',
            fields=[
                ('tr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tr_tid', models.IntegerField()),
                ('tr_sid', models.IntegerField()),
                ('tr_type', models.IntegerField()),
                ('tr_tone', models.IntegerField()),
                ('tr_text', models.TextField()),
                ('tr_flag', models.IntegerField()),
            ],
        ),
    ]
