# Generated by Django 5.2.5 on 2025-09-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xception',
            fields=[
                ('xc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('xc_year', models.IntegerField()),
                ('xc_month', models.IntegerField()),
                ('xc_day', models.IntegerField()),
                ('xc_new_month', models.IntegerField()),
                ('xc_new_day', models.IntegerField()),
                ('xc_note', models.TextField()),
                ('xc_flag', models.IntegerField()),
            ],
        ),
    ]
