# Generated by Django 5.2.5 on 2025-09-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Life',
            fields=[
                ('lives_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lives_sid', models.IntegerField()),
                ('lives_name', models.CharField(max_length=200)),
                ('lives_text', models.TextField()),
                ('lives_flag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menaion',
            fields=[
                ('mn_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mn_month', models.IntegerField()),
                ('mn_day', models.IntegerField()),
                ('mn_sid', models.IntegerField()),
                ('mn_name', models.CharField(max_length=200)),
                ('mn_alpha', models.CharField(blank=True, max_length=50, null=True)),
                ('mn_fname', models.CharField(blank=True, max_length=200, null=True)),
                ('mn_gender', models.CharField(blank=True, max_length=50, null=True)),
                ('mn_date', models.CharField(blank=True, max_length=50, null=True)),
                ('mn_loc', models.CharField(blank=True, max_length=200, null=True)),
                ('mn_disp', models.CharField(blank=True, max_length=50, null=True)),
                ('mn_flevel', models.IntegerField()),
                ('mn_fast', models.IntegerField()),
                ('mn_collect', models.IntegerField()),
                ('mn_indiv', models.IntegerField()),
                ('mn_icon', models.CharField(blank=True, max_length=200, null=True)),
                ('mn_flag', models.IntegerField()),
                ('mn_sermon_url', models.CharField(blank=True, max_length=200, null=True)),
                ('mn_sort', models.IntegerField()),
            ],
        ),
    ]
