# Generated by Django 5.2.5 on 2025-09-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('icon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('icon_category', models.IntegerField()),
                ('icon_month', models.IntegerField()),
                ('icon_day', models.IntegerField()),
                ('icon_dday', models.CharField(blank=True, max_length=50, null=True)),
                ('icon_idx', models.IntegerField()),
                ('icon_sid', models.IntegerField()),
                ('icon_name', models.CharField(max_length=200)),
                ('icon_icon', models.CharField(blank=True, max_length=200, null=True)),
                ('icon_flag', models.IntegerField()),
            ],
        ),
    ]
